#!/usr/bin/env python3
"""Regenerate assets/js/kg-data.js from the CSV files in data/.

The landing page renders its charts (node/relation distributions, evidence
tiers, TEC histogram, dynasty timeline, central nodes, CMS heatmap, file sizes)
from this embedded JSON so that no runtime CSV parsing is needed on index.html.

Usage:  python3 scripts/build_kg_data.py
"""
import collections
import csv
import json
import os
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "assets" / "js" / "kg-data.js"
GRAPH_OUT = ROOT / "assets" / "data" / "kg_graph.json"


def read(name):
    with open(DATA / name, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def main():
    nodes = read("kg_nodes.csv")
    edges = read("kg_edges.csv")
    cms = read("cms_classical_to_modern_anchor.csv")

    out = {}
    out["nodeTypes"] = collections.Counter(n["type"] for n in nodes).most_common()
    out["relations"] = collections.Counter(e["relation"] for e in edges).most_common()
    out["edgeClass"] = dict(collections.Counter(e["edge_class"] for e in edges))
    out["tiers"] = dict(collections.Counter(e["evidence_tier"] for e in edges if e["evidence_tier"]))
    out["dynasties"] = collections.Counter(n["dynasty"] for n in nodes if n["type"] == "古籍").most_common()

    top = sorted(nodes, key=lambda n: -float(n["betweenness"] or 0))[:12]
    out["topNodes"] = [
        {
            "type": n["type"],
            "name": n["name"],
            "betweenness": float(n["betweenness"] or 0),
            "degree": int(n["degree"]),
            "passages": int(float(n["n_passages"] or 0)),
        }
        for n in top
    ]

    tec = [float(e["TEC_t"]) for e in edges if e["TEC_t"]]
    bins = [0] * 10
    for t in tec:
        bins[min(int(t * 10), 9)] += 1
    out["tecHist"] = bins

    out["cms"] = [
        {k: (v if k in ("classical_concept", "modern_anchor") else float(v)) for k, v in r.items()}
        for r in cms
    ]

    for t, key in [("中药", "herbs"), ("方剂", "formulas"), ("腧穴", "acupoints"), ("古籍", "books")]:
        tt = sorted([n for n in nodes if n["type"] == t], key=lambda n: -int(n["degree"]))[:10]
        out[key] = [
            {"name": n["name"], "degree": int(n["degree"]), "year": n["year"] or None, "dynasty": n["dynasty"] or None}
            for n in tt
        ]

    out["files"] = [{"name": f, "bytes": os.path.getsize(DATA / f)} for f in sorted(os.listdir(DATA))]

    OUT.write_text(
        "/* Auto-generated by scripts/build_kg_data.py from data/*.csv — do not edit by hand. */\n"
        "window.KG_DATA = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(nodes)} nodes, {len(edges)} edges, {len(cms)} CMS rows")

    # Compact graph for the interactive explorer (integer-indexed, no CSV parsing at runtime)
    idx = {n["node_id"]: i for i, n in enumerate(nodes)}
    gnodes = []
    for n in nodes:
        g = {"id": n["node_id"], "t": n["type"], "n": n["name"], "d": int(n["degree"]), "b": round(float(n["betweenness"] or 0), 4)}
        if n["n_passages"]:
            g["p"] = int(float(n["n_passages"]))
        if n["year"]:
            g["y"] = int(float(n["year"]))
        if n["dynasty"]:
            g["dy"] = n["dynasty"]
        if n["drug_category"]:
            g["dc"] = n["drug_category"]
        if n["meridian"]:
            g["me"] = n["meridian"]
        if n["anchor_category"]:
            g["ac"] = n["anchor_category"]
        if n["anchor_name_zh"]:
            g["az"] = n["anchor_name_zh"]
        gnodes.append(g)
    cls = {"evidence": "e", "structural": "s", "bridge_score": "b"}
    gedges = []
    for e in edges:
        if e["source_id"] not in idx or e["target_id"] not in idx:
            continue
        w = e["TEC_t"] or e["mapping_score"] or ""
        gedges.append([idx[e["source_id"]], idx[e["target_id"]], e["relation"], round(float(w), 3) if w else None, e["evidence_tier"] or "", cls.get(e["edge_class"], "e")])
    GRAPH_OUT.parent.mkdir(parents=True, exist_ok=True)
    GRAPH_OUT.write_text(json.dumps({"nodes": gnodes, "edges": gedges}, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"wrote {GRAPH_OUT.relative_to(ROOT)}: {GRAPH_OUT.stat().st_size // 1024} KB")


if __name__ == "__main__":
    main()
